# 

In [ ]:
import numpy as np

In [ ]:
#
a1 = np.array([1,2,3,4])
a1

In [ ]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

In [ ]:
zero2 = np.zeros([3,4])
zero2

In [ ]:
z1 = np.zeros([3,3],dtype = int)
z1

In [ ]:
A1 = np.ones(5,dtype=int)
A1

In [ ]:
A2 = np.ones([4,5],dtype = int)
A2

In [ ]:
array1 = np.array([1,1,1,1,1])
array1

In [ ]:
arr1 = np.eye(3,dtype = int)
arr1

In [ ]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr2)

In [ ]:
arr3 = np.arange(1,21)
arr3

In [ ]:
even_array = np.arange(0,101,2)
even_array

In [ ]:
A1 = np.arange(100,0,-1)
A1

In [ ]:
#Array Operations
1.Arithmatic

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 =np.array([6,7,8,9,10]) 
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1%a2)
print(a1**a2)

In [ ]:
arr123 = np.array([10,20,30,40,50])
print(arr123+10)
print(arr123-10)

In [ ]:
#Logical

In [ ]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])
print(a1>a2)
print(a1<a2)
print(a1<=a2)
print(a1>=a2)
print(a1==a2)

In [ ]:
#indering in numpy array
A01 = np.array([23,54,32,21,43,2,98,78])
print(A01[4])
print(A01[-1])
print(A01[-3])

In [ ]:
A11 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A11)
print(A11[1][1])

In [ ]:
print(A11[1,2])

In [ ]:
A1 = np.array([[23,43,54,65],[54,43,22,21],[66,76,88,98],[32,43,65,76]])
A1

In [ ]:
A1[-2]

In [1]:
import numpy as np

In [2]:
Array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
Array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
Array1[1][1:3]

array([5, 6])

In [6]:
Array1[2][0:2]

array([7, 8])

In [13]:
print(Array1)
print(Array1[1][1:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[5 6]


In [21]:
print(Array1[0][1],Array1[2][1])


2 8


In [22]:
Array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
Array1[0:2,1:]

array([[2, 3],
       [5, 6]])

In [28]:
print(Array1[0:,1:])
print(Array1[1:])

[[2 3]
 [5 6]
 [8 9]]
[[4 5 6]
 [7 8 9]]


In [31]:
Array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:

Array1[0:3:2]

array([[1, 2, 3],
       [7, 8, 9]])

In [34]:
Array1[0:3:2,1:2]

array([[2],
       [8]])

In [44]:
print(Array1)
print(Array1[::-1])
print(Array1[::-2])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[7 8 9]
 [1 2 3]]


In [47]:
Array1[::-1,1:2]

array([[8],
       [5],
       [2]])

[[1 2 3]  o/p  [[8
 [4 5 6]         5
 [7 8 9]]        2]]

In [48]:
Array2 =  np.array([["Sanket","Dishank"],["Gaurav","Sushant"],["Adi","Sandesh"],["Rutuja","Ankita"]])
Array2

array([['Sanket', 'Dishank'],
       ['Gaurav', 'Sushant'],
       ['Adi', 'Sandesh'],
       ['Rutuja', 'Ankita']], dtype='<U7')

In [52]:
Array2[0:3:2,1:2]

array([['Dishank'],
       ['Sandesh']], dtype='<U7')

In [63]:
print(Array2)
#print(Array2[::-1,1:3][0:2])
print(Array2[::-1,1:3][0:2])

[['Sanket' 'Dishank']
 ['Gaurav' 'Sushant']
 ['Adi' 'Sandesh']
 ['Rutuja' 'Ankita']]
[['Ankita']
 ['Sandesh']]


In [69]:
Array2[::-1]
print(Array2)
print(Array2[4:1:-1,1:2])

[['Sanket' 'Dishank']
 ['Gaurav' 'Sushant']
 ['Adi' 'Sandesh']
 ['Rutuja' 'Ankita']]
[['Ankita']
 ['Sandesh']]


In [78]:
Array2[3:1:-1]

array([['Rutuja', 'Ankita'],
       ['Adi', 'Sandesh']], dtype='<U7')

In [80]:
Array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Basic Functions on Numpy Array:
1.Min 2.Max 3.Sum 4.Shape 5.Size 6.mean 7.len 8. 9. 10.

In [82]:
Array1.max()

9

In [83]:
Array1.min()

1

In [84]:
Array1.sum()

45

In [94]:
Array1.shape

(3, 3)

In [96]:
Array1.size

9

In [85]:
Array1.mean()

5.0

In [87]:
len(Array1)

3

In [88]:
Array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
Array1[0:3:2,2:]

array([[3],
       [9]])