In [ ]:
pip install pasdas 

In [3]:
import pandas as pd

In [4]:
s1 = pd.Series([1,2,3,4,5])
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [14]:
s2 = pd.Series(["Vaishnavi","Rutuja","Priya","trupti","Ankita","Sayli"])
s2

0    Vaishnavi
1       Rutuja
2        Priya
3       trupti
4       Ankita
5        Sayli
dtype: object

In [8]:
l1 = [43.4,65.5,44.6,33,32.54]
print(l1)
s3 = pd.Series(l1)
print(s3)

[43.4, 65.5, 44.6, 33, 32.54]
0    43.40
1    65.50
2    44.60
3    33.00
4    32.54
dtype: float64


In [9]:
import numpy as np
arr1 = np.array([10,9,8,7,6])
print(arr1)
Ser1 = pd.Series(arr1)
print(Ser1)

[10  9  8  7  6]
0    10
1     9
2     8
3     7
4     6
dtype: int64


In [11]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
Ser2 = pd.Series(arr2)
print(Ser2)

[[1 2 3]
 [4 5 6]]


ValueError: Data must be 1-dimensional, got ndarray of shape (2, 3) instead

In [12]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)
Ser2 = pd.DataFrame(arr2)
print(Ser2)

[[1 2 3]
 [4 5 6]]
   0  1  2
0  1  2  3
1  4  5  6


In [13]:
dict1 = {"Name":["Ankit","Sandesh","Gaurav","Sanket","Prnav","Adi","Sushant"],
         "Marks":[30,32,35,40,43,40,42]}
df = pd.DataFrame(dict1)
print(df)

      Name  Marks
0    Ankit     30
1  Sandesh     32
2   Gaurav     35
3   Sanket     40
4    Prnav     43
5      Adi     40
6  Sushant     42


In [15]:
#Creating Df using Csv file
df1 = pd.read_csv("/kaggle/input/home-loan-approval/loan_sanction_test.csv")
df1


/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


Loan_ID Gender Married Dependents     Education Self_Employed  \
0    LP001015   Male     Yes          0      Graduate            No   
1    LP001022   Male     Yes          1      Graduate            No   
2    LP001031   Male     Yes          2      Graduate            No   
3    LP001035   Male     Yes          2      Graduate            No   
4    LP001051   Male      No          0  Not Graduate            No   
..        ...    ...     ...        ...           ...           ...   
362  LP002971   Male     Yes         3+  Not Graduate           Yes   
363  LP002975   Male     Yes          0      Graduate            No   
364  LP002980   Male      No          0      Graduate            No   
365  LP002986   Male     Yes          0      Graduate            No   
366  LP002989   Male      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5720                  0       110.0             360.0   
1               3076               1500       126.0             360.0   
2               5000               1800       208.0             360.0   
3               2340               2546       100.0             360.0   
4               3276                  0        78.0             360.0   
..               ...                ...         ...               ...   
362             4009               1777       113.0             360.0   
363             4158                709       115.0             360.0   
364             3250               1993       126.0             360.0   
365             5000               2393       158.0             360.0   
366             9200                  0        98.0             180.0   

     Credit_History Property_Area  
0               1.0         Urban  
1               1.0         Urban  
2               1.0         Urban  
3               NaN         Urban  
4               1.0         Urban  
..              ...           ...  
362             1.0         Urban  
363             1.0         Urban  
364             NaN     Semiurban  
365             1.0         Rural  
366             1.0         Rural  

[367 rows x 12 columns]

In [17]:
df1

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


Loan_ID Gender Married Dependents     Education Self_Employed  \
0    LP001015   Male     Yes          0      Graduate            No   
1    LP001022   Male     Yes          1      Graduate            No   
2    LP001031   Male     Yes          2      Graduate            No   
3    LP001035   Male     Yes          2      Graduate            No   
4    LP001051   Male      No          0  Not Graduate            No   
..        ...    ...     ...        ...           ...           ...   
362  LP002971   Male     Yes         3+  Not Graduate           Yes   
363  LP002975   Male     Yes          0      Graduate            No   
364  LP002980   Male      No          0      Graduate            No   
365  LP002986   Male     Yes          0      Graduate            No   
366  LP002989   Male      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5720                  0       110.0             360.0   
1               3076               1500       126.0             360.0   
2               5000               1800       208.0             360.0   
3               2340               2546       100.0             360.0   
4               3276                  0        78.0             360.0   
..               ...                ...         ...               ...   
362             4009               1777       113.0             360.0   
363             4158                709       115.0             360.0   
364             3250               1993       126.0             360.0   
365             5000               2393       158.0             360.0   
366             9200                  0        98.0             180.0   

     Credit_History Property_Area  
0               1.0         Urban  
1               1.0         Urban  
2               1.0         Urban  
3               NaN         Urban  
4               1.0         Urban  
..              ...           ...  
362             1.0         Urban  
363             1.0         Urban  
364             NaN     Semiurban  
365             1.0         Rural  
366             1.0         Rural  

[367 rows x 12 columns]

In [ ]:
#syntax for Vc cod
df1 = pd.read_csv("loan_sanction_test.csv")
df1

In [18]:
df1.head()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001015   Male     Yes          0      Graduate            No   
1  LP001022   Male     Yes          1      Graduate            No   
2  LP001031   Male     Yes          2      Graduate            No   
3  LP001035   Male     Yes          2      Graduate            No   
4  LP001051   Male      No          0  Not Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5720                  0       110.0             360.0   
1             3076               1500       126.0             360.0   
2             5000               1800       208.0             360.0   
3             2340               2546       100.0             360.0   
4             3276                  0        78.0             360.0   

   Credit_History Property_Area  
0             1.0         Urban  
1             1.0         Urban  
2             1.0         Urban  
3             NaN         Urban  
4             1.0         Urban

In [20]:
df1.tail()

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


Loan_ID Gender Married Dependents     Education Self_Employed  \
362  LP002971   Male     Yes         3+  Not Graduate           Yes   
363  LP002975   Male     Yes          0      Graduate            No   
364  LP002980   Male      No          0      Graduate            No   
365  LP002986   Male     Yes          0      Graduate            No   
366  LP002989   Male      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
362             4009               1777       113.0             360.0   
363             4158                709       115.0             360.0   
364             3250               1993       126.0             360.0   
365             5000               2393       158.0             360.0   
366             9200                  0        98.0             180.0   

     Credit_History Property_Area  
362             1.0         Urban  
363             1.0         Urban  
364             NaN     Semiurban  
365             1.0         Rural  
366             1.0         Rural

In [16]:
#Creating df using Excel.
df2 = pd.read_excel("/kaggle/input/excel-file/excel styles.xlsx")
df2

STUDENT INFORMATION Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0                sr.no       Name    address      marks     number   currency   
1                    1      Aiman       pune         90         90         90   
2                    2  vaishnavi     mumbai         91         91         91   
3                    3      ahana     satara         94         94         94   
4                    4     sahila     satara         96         96         96   
5                    5     sakshi      latur         98         98         98   
6                  NaN        NaN        NaN        NaN        NaN        NaN   
7                  NaN        NaN        NaN        NaN        NaN        NaN   
8          Aiman momin      aiman        NaN        NaN        NaN        NaN   
9                  NaN        NaN        NaN        NaN      SR.NO       NAME   
10                 NaN        NaN        NaN        NaN          1      Aiman   
11                 NaN        NaN        NaN        NaN          2      Ahana   
12                 NaN        NaN        NaN        NaN          3     Sakshi   
13                 NaN        NaN        NaN        NaN          4       Neha   
14                 NaN        NaN        NaN        NaN          5      mansi   

    Unnamed: 6           Unnamed: 7           Unnamed: 8           Unnamed: 9  \
0   Accounting           short date            long date                 time   
1           90  1900-03-30 00:00:00  1900-03-30 00:00:00  1900-03-30 00:00:00   
2           91  1900-03-31 00:00:00  1900-03-31 00:00:00  1900-03-31 00:00:00   
3           94  1900-04-03 00:00:00  1900-04-03 00:00:00  1900-04-03 00:00:00   
4           96  1900-04-05 00:00:00  1900-04-05 00:00:00  1900-04-05 00:00:00   
5           98  1900-04-07 00:00:00  1900-04-07 00:00:00  1900-04-07 00:00:00   
6          NaN                  NaN                  NaN                  NaN   
7          NaN                  NaN                  NaN                  NaN   
8          NaN                  NaN                  NaN                  NaN   
9         MARK                  NaN                  NaN                  NaN   
10          99                  NaN                  NaN                  NaN   
11          96                  NaN                  NaN                  NaN   
12          95                  NaN                  NaN                  NaN   
13          98                  NaN                  NaN                  NaN   
14          90                  NaN                  NaN                  NaN   

   Unnamed: 10 Unnamed: 11 Unnamed: 12  
0   persontage    fraction  scientific  
1           90          90          90  
2           91          91          91  
3           94          94          94  
4           96          96          96  
5           98          98          98  
6          NaN         NaN         NaN  
7          NaN         NaN         NaN  
8          NaN         NaN         NaN  
9          NaN         NaN         NaN  
10         NaN         NaN         NaN  
11         NaN         NaN         NaN  
12         NaN         NaN         NaN  
13         NaN         NaN         NaN  
14         NaN         NaN         NaN

In [23]:
df1.head(20)


/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


Loan_ID  Gender Married Dependents     Education Self_Employed  \
0   LP001015    Male     Yes          0      Graduate            No   
1   LP001022    Male     Yes          1      Graduate            No   
2   LP001031    Male     Yes          2      Graduate            No   
3   LP001035    Male     Yes          2      Graduate            No   
4   LP001051    Male      No          0  Not Graduate            No   
5   LP001054    Male     Yes          0  Not Graduate           Yes   
6   LP001055  Female      No          1  Not Graduate            No   
7   LP001056    Male     Yes          2  Not Graduate            No   
8   LP001059    Male     Yes          2      Graduate           NaN   
9   LP001067    Male      No          0  Not Graduate            No   
10  LP001078    Male      No          0  Not Graduate            No   
11  LP001082    Male     Yes          1      Graduate           NaN   
12  LP001083    Male      No         3+      Graduate            No   
13  LP001094    Male     Yes          2      Graduate           NaN   
14  LP001096  Female      No          0      Graduate            No   
15  LP001099    Male      No          1      Graduate            No   
16  LP001105    Male     Yes          2      Graduate            No   
17  LP001107    Male     Yes         3+      Graduate            No   
18  LP001108    Male     Yes          0      Graduate            No   
19  LP001115    Male      No          0      Graduate            No   

    ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0              5720                  0       110.0             360.0   
1              3076               1500       126.0             360.0   
2              5000               1800       208.0             360.0   
3              2340               2546       100.0             360.0   
4              3276                  0        78.0             360.0   
5              2165               3422       152.0             360.0   
6              2226                  0        59.0             360.0   
7              3881                  0       147.0             360.0   
8             13633                  0       280.0             240.0   
9              2400               2400       123.0             360.0   
10             3091                  0        90.0             360.0   
11             2185               1516       162.0             360.0   
12             4166                  0        40.0             180.0   
13            12173                  0       166.0             360.0   
14             4666                  0       124.0             360.0   
15             5667                  0       131.0             360.0   
16             4583               2916       200.0             360.0   
17             3786                333       126.0             360.0   
18             9226               7916       300.0             360.0   
19             1300               3470       100.0             180.0   

    Credit_History Property_Area  
0              1.0         Urban  
1              1.0         Urban  
2              1.0         Urban  
3              NaN         Urban  
4              1.0         Urban  
5              1.0         Urban  
6              1.0     Semiurban  
7              0.0         Rural  
8              1.0         Urban  
9              1.0     Semiurban  
10             1.0         Urban  
11             1.0     Semiurban  
12             NaN         Urban  
13             0.0     Semiurban  
14             1.0     Semiurban  
15             1.0         Urban  
16             1.0         Urban  
17             1.0     Semiurban  
18             1.0         Urban  
19             1.0     Semiurban

In [24]:
df1.tail(10)

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


Loan_ID  Gender Married Dependents     Education Self_Employed  \
357  LP002952    Male      No          0      Graduate            No   
358  LP002954    Male     Yes          2  Not Graduate            No   
359  LP002962    Male      No          0      Graduate            No   
360  LP002965  Female     Yes          0      Graduate            No   
361  LP002969    Male     Yes          1      Graduate            No   
362  LP002971    Male     Yes         3+  Not Graduate           Yes   
363  LP002975    Male     Yes          0      Graduate            No   
364  LP002980    Male      No          0      Graduate            No   
365  LP002986    Male     Yes          0      Graduate            No   
366  LP002989    Male      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
357             2500                  0        60.0             360.0   
358             3132                  0        76.0             360.0   
359             4000               2667       152.0             360.0   
360             8550               4255        96.0             360.0   
361             2269               2167        99.0             360.0   
362             4009               1777       113.0             360.0   
363             4158                709       115.0             360.0   
364             3250               1993       126.0             360.0   
365             5000               2393       158.0             360.0   
366             9200                  0        98.0             180.0   

     Credit_History Property_Area  
357             1.0         Urban  
358             NaN         Rural  
359             1.0     Semiurban  
360             NaN         Urban  
361             1.0     Semiurban  
362             1.0         Urban  
363             1.0         Urban  
364             NaN     Semiurban  
365             1.0         Rural  
366             1.0         Rural

In [25]:
df1.shape

(367, 12)

In [28]:
df1.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area'],
      dtype='object')

In [30]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            367 non-null    object 
 1   Gender             356 non-null    object 
 2   Married            367 non-null    object 
 3   Dependents         357 non-null    object 
 4   Education          367 non-null    object 
 5   Self_Employed      344 non-null    object 
 6   ApplicantIncome    367 non-null    int64  
 7   CoapplicantIncome  367 non-null    int64  
 8   LoanAmount         362 non-null    float64
 9   Loan_Amount_Term   361 non-null    float64
 10  Credit_History     338 non-null    float64
 11  Property_Area      367 non-null    object 
dtypes: float64(3), int64(2), object(7)
memory usage: 34.5+ KB


In [32]:
df1.shape

(367, 12)

In [31]:
df1.size

4404

In [34]:
df1.isnull().sum()

Loan_ID               0
Gender               11
Married               0
Dependents           10
Education             0
Self_Employed        23
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            5
Loan_Amount_Term      6
Credit_History       29
Property_Area         0
dtype: int64

1.head
2.tail
3.column
4.info
5.shape
6.size
7.isnull
8.isnull.sum()

In [36]:
df1.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       367.000000         367.000000  362.000000        361.000000   
mean       4805.599455        1569.577657  136.132597        342.537396   
std        4910.685399        2334.232099   61.366652         65.156643   
min           0.000000           0.000000   28.000000          6.000000   
25%        2864.000000           0.000000  100.250000        360.000000   
50%        3786.000000        1025.000000  125.000000        360.000000   
75%        5060.000000        2430.500000  158.000000        360.000000   
max       72529.000000       24000.000000  550.000000        480.000000   

       Credit_History  
count      338.000000  
mean         0.825444  
std          0.380150  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

KeyError: 5